# Generated by Django 3.1.3 on 2020-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='fecha_de_turno',
            field=models.DateField(auto_now_add=True, verbose_name='fecha de turno'),
        ),
    ]
